HW2 is completed
aplab/hw-test pull request #2
Opened 2022-06-08 06:51 UTC by aplab

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-09 15:17 UTC, alexus1024 requested changes

2022-06-09 15:17 UTC, alexus1024 commented on hw02_unpack_string/unpack.go
> +					b.Reset()
не могу принять такое решение по работе с билдером.
Сброс и переписывание его - нивелирует приемущество от его использования, а так же такое решение плохо переносится на практику, где у вас на выходе может быть поток без функции сброса.

Давайте тут приведём решение к подходу, когда в билдер мы только пишем, а в строку переводим его один раз, в конце, для вывода результата.

2022-06-09 15:31 UTC, aplab commented on hw02_unpack_string/unpack.go
> +					b.Reset()
Обязательно ли использовать билдер?

2022-06-10 13:41 UTC, alexus1024 commented on hw02_unpack_string/unpack.go
> +					b.Reset()
ну, не обязательно, но я не знаю как бы ещё сделать , чтобы было эффективно и удобно

2022-06-10 13:45 UTC, alexus1024 approved these changes

2022-06-10 13:45 UTC, alexus1024 commented on hw02_unpack_string/unpack_test.go
> +		{input: []rune(`\`)[0], expected: true},
не понял чем это отличается от `'\\'`

2022-06-10 13:54 UTC, aplab commented on hw02_unpack_string/unpack_test.go
> +		{input: []rune(`\`)[0], expected: true},
в конечном итоге ничем, просто иная запись

2022-06-13 22:46 UTC, alexus1024 approved these changes

2022-06-13 22:48 UTC, alexus1024 approved these changes

2022-06-13 22:48 UTC, alexus1024 approved these changes

2022-06-14 18:24 UTC, merged